### ISSUE TITLE
Error during node-gyp rebuild

### ISSUE THREAD

**Issue by vincelwt** [tcr/mediakeys#3]
[log.txt](https://github.com/tcr/mediakeys/files/113750/log.txt)

**Comment by tcr** [comment]
Resolved by #4.

**Comment by admorris** [comment]
The fix seems to only cover OSX, but I get identical errors on Fedora 24

[npm-debug.txt](https://github.com/tcr/mediakeys/files/649719/npm-debug.txt)

[npm_install_output.txt](https://github.com/tcr/mediakeys/files/649733/npm_install_output.txt)
